version: 2
updates:
- package-ecosystem: npm
  directory: "/api"
  schedule:
    interval: daily
    time: '23:30'
    timezone: Asia/Calcutta
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/v1"
  schedule:
    interval: daily
    time: '23:30'
    timezone: Asia/Calcutta
  open-pull-requests-limit: 10
  - package-ecosystem: npm
  directory: "/v2"
  schedule:
    interval: daily
    time: '23:30'
    timezone: Asia/Calcutta
  open-pull-requests-limit: 10
