name: GAE Deploy

on:
  push:
    branches: 
      - master
jobs:
  testfront:
   name: Test Frontend
   runs-on: ubuntu-latest

   env:
     client: ./www/client
     admin: ./admin/client

   steps:
     - name: Checkout
       uses: actions/checkout@v2

     - name: Node Setup
       uses: actions/setup-node@v1
       with:
        node-version: 12

     - name: NPM Install WWW
       run: npm ci
       working-directory: ${{env.client}}

     - name: Test WWW
       run: npm test
       working-directory: ${{env.client}}
     
     - name: NPM Install admin
       run: npm ci
       working-directory: ${{env.admin}}

     - name: Test admin
       run: npm test
       working-directory: ${{env.admin}}

#   testback:
#     name: Test Backend
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2

#       - name: Node Setup
#         uses: actions/setup-node@v1
#         with:
#           node-version: 12

#       - name: NPM Install
#         run: npm ci

#       - name: Test Backend
#         run: npm test

  build:
    name: Build & Deploy
    runs-on: ubuntu-latest
    needs: [testfront]

    env:
     client: ./www/client
     admin: ./admin/client

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Node Setup
        uses: actions/setup-node@v1
        with:
          node-version: 12
      
      - name: GAE Setup
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          project_id: ${{ secrets.PROJECT_ID }}
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS}}

      - name: NPM Install WWW
        run: npm ci
        working-directory: ${{env.client}}

      - name: Build WWW
        run: npm run build
        working-directory: ${{env.client}}
      
      - name: NPM Install admin
        run: npm ci
        working-directory: ${{env.admin}}

      - name: Build admin
        run: npm run build
        working-directory: ${{env.admin}}
      
#       - name: ENV vars
#         run: |
#           echo '
#            recapta: '${{ secrets.RECAPTA_PRIVATE_KEY }} >> app.yaml
#           echo ' MAIL_SENDER: '${{ secrets.MAIL_SENDER }} >> app.yaml
#           echo ' MAIL_REPLYTO: '${{ secrets.MAIL_REPLYTO }} >> app.yaml
#           echo ' SENDGRID_API: '${{ secrets.SENDGRID_API }} >> app.yaml
#           echo ' mongoConnect: '${{ secrets.MONGODB_CONNECT }} >> app.yaml
#           echo ' mongouser: '${{ secrets.MONGODB_USER }} >> app.yaml
#           echo ' mongopass: '${{ secrets.MONGODB_PASS }} >> app.yaml
#           cat app.yaml
      
      # Deploy App to App Engine
      - name: Deploy
        run: |
          gcloud app deploy www/app.yaml api/app.yaml admin/app.yaml dispatch.yaml --quiet
