name: GAE Deploy

on:
  push:
    branches:
      - master

jobs:
  test_build:
    name: Build & Deploy
    runs-on: ubuntu-latest

    env:
      client: ./v1

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Node Setup
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: GAE Setup
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          project_id: ${{ secrets.PROJECT_ID }}
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS}}

      - name: NPM Install WWW
        run: npm ci
        working-directory: ${{env.client}}

      - name: Test WWW
        run: npm test
        working-directory: ${{env.client}}

      - name: Build WWW
        run: npm run build
        working-directory: ${{env.client}}

      # Deploy App to App Engine
      - name: Deploy
        run: |
          gcloud app deploy www/app.yaml dispatch.yaml --quiet
#          gcloud app deploy www/app.yaml api/app.yaml admin/app.yaml dispatch.yaml --quiet
